### ISSUE TITLE
Construction fails if `titleFormat` is missing from a locale (Cannot read properties of undefined (reading 'toDisplay'))

### ISSUE THREAD

**Issue by szotsaki** [mymth/vanillajs-datepicker#141]
According to the [documentation](https://mymth.github.io/vanillajs-datepicker/#/i18n?id=custom-locale)
> You can omit properties that can fallback to en:English (US).

However, if you omit `titleFormat`, construction will fail when the second call to https://github.com/mymth/vanillajs-datepicker/blob/9de5051545626b116db3d213b0b1e429f296967c/js/lib/date-format.js#L180 will result in `format` being `undefined`:

```
datepicker.js:377 Uncaught TypeError: Cannot read properties of undefined (reading 'toDisplay')
    at formatDate (datepicker.js:377:16)
    at DaysView.render (datepicker.js:1244:9)
    at new Picker (datepicker.js:1829:24)
    at new Datepicker (datepicker.js:2456:36)
```

This attribute was not part of the Bootstrap datepicker locale array, therefore direct use of its locale settings won't work.

**Comment by szotsaki** [comment]
This is bug is only valid if you'd like to override the `en` locale, which is not supposed to, I assume.
